### ISSUE TITLE
Support friendly projectile.

### ISSUE THREAD

**Issue by sors89** [Soof4/PrimeBombToMissile#1]
This is a really nice plugin, keep up the good work dude!

Currently, this plugin is only support hostile projectile. If you change to friendly hostile like Boulder from Staff of Earth, its end up damaging itself and the Boulder does not deal any damage to player either. Is there any ways to support friendly projectile as well?

**Comment by LiteralSoofa** [comment]
Thank you!

There should be a way to change the projectile's source (idk how rn). I'll give it a shot in a few weeks to see if i can do it.

**Comment by sors89** [comment]
> Thank you!
> 
> 
> 
> There should be a way to change the projectile's source (idk how rn). I'll give it a shot in a few weeks to see if i can do it.

Good luck dude! Thanks for your effort. 

Also how do i change the projectile's velocity so its always point at player?

**Comment by LiteralSoofa** [comment]
That would be hard to add, first you would need to calculate which player will be targeted and then do calculation to point it towards the player. I can't help much about this, sorry.

**Comment by LiteralSoofa** [comment]
Due to API limitations, it's not possible to change a projectile's hostility and send a packet with this information. Sad :(
